name: CI workflow

on: 
  push:
    branches: ["main", "make-ci-better-yah"]
  pull_request:
    branches: ["main", "make-ci-better-yah"]

defaults:
  run:
    working-directory: ./lab2/TDD

jobs: 
  build: 
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      # Adding security analysis with Bandit
      - name: Security analysis with Bandit
        run: |
          pip install bandit
          bandit -r src -f json -o bandit-report.json
          cat bandit-report.json

      # Run unit tests with pytest
      - name: Run unit tests with pytest
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing

  test_python_3_8:  # New job for Python 3.8
    runs-on: ubuntu-latest
    container: python:3.8-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing

  test_python_3_10:  # New job for Python 3.10
    runs-on: ubuntu-latest
    container: python:3.10-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
